### ISSUE TITLE
customizationSpec is never applied to new vm.

### ISSUE THREAD

**Issue by ThePSAdmin** [devblackops/POSHOrigin_vSphere#39]
When providing the name of the customizationSpec, it is never applied to the newly created VM. 

## Expected Behavior
The OS customization spec should be applied to the VM

## Possible Solution
Add the customizationSpec to the parameter splat for new-vm in _CreateVM.ps1. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Module version used:
* Operating System and PowerShell version:

**Comment by devblackops** [comment]
Hi @ThePSAdmin. The customizationSpec is actually applied during the NIC configuration here: https://github.com/devblackops/POSHOrigin_vSphere/blob/dev/POSHOrigin_vSphere/DSCResources/POSHOrigin_vSphere_VM/Helpers/_SetVMNICs.ps1#L236. It is a odd place to be applying it though.

Are you seeing any problems with the spec not being applied to newly created VMs?

**Comment by ThePSAdmin** [comment]
Hi, I was having a few problems since I'm using the dsc resources from a normal dsc configuration instead of through posh_origin, and I ended up shaving yaks and thought I saw a (this) problem in the process. Will close. Sorry!
